### PR TITLE
transfer out date

### LINKED ISSUE #61: [ART] Transfer out date on Transfer Out Note is set to session date instead of transfer out date
## How to reproduce

Using the ART application, register a patient on date in the past. Transfer out the patient on the same day or any day in the past but after the registration date. Print a Transfer out note on some other date. The transfer out date on the note will get set to the session date instead of the transfer out date which is stored as the outcome (ie patient_state) start_date.

## Notes

- The note can also be accessed directly from the API through: `GET /api/v1/programs/1/patients/:patient_id/labels/transfer_out`
- The current implementation of the note is located at [/app/services/art_service/patient_transfer_out_label.rb](https://github.com/HISMalawi/BHT-EMR-API/blob/development/app/services/art_service/patient_transfer_out_label.rb)

### PR DESCRIPTION
**Pull request by Skipper-116**
Added logic to fetch an actual transfer out date instead of using the session date

Closes #61

### CODE REVIEW

File: app/services/art_service/patient_transfer_out_label.rb [hunk 1]
```diff
@@ -101,9 +101,23 @@ def print
...
       label.print(1)
     end
+
+    # method to get transfer out date
+    def actual_transfer_out_date
+      record = PatientState
+               .joins(
+                 'LEFT JOIN (patient_program) on (patient_state.patient_program_id = patient_program.patient_program_id)'
+               )
+               .where('patient_program.patient_id = ?', patient.patient_id)
```
Comment (ntumbuka) [inline app/services/art_service/patient_transfer_out_label.rb]: You should also limit this to the HIV Program. Something like:

```ruby
.where(patient_program: { patient_id: patient.patient_id, program_id: Program.find_by_name!('HIV Program').program_id })
```

**Review by ntumbuka — CHANGES_REQUESTED** [review]
Looks okay... You just need to specify the program_id to limit your query to ART.

**Review by ntumbuka — APPROVED** [review]
